### PR TITLE
Added type definitions to MTM relations in examples

### PR DESCRIPTION
**Pull request by FOSSforlife**
This was causing errors when I was trying to run the examples. Easy fix :)

### CODE REVIEW

**Comment by goldcaddy77** [comment]
Awesome, thanks for the PR!

**Comment by goldcaddy77** [comment]
So that I can make sure this doesn't happen again, what command were you running?

**Comment by FOSSforlife** [comment]
I believe it was happening whenever I ran `yarn codegen`.

**Pull request merged**
