### PR TITLE
feat(models): Allow fields to be nullable in graphql create inputs but non-nullable in tables

### PR DESCRIPTION
**Pull request by ikoenigsknecht**

### CODE REVIEW

**Comment by goldcaddy77** [comment]
What's the use-case here? Why would you want this to be possible?

**Comment by ikoenigsknecht** [comment]
@goldcaddy77 The use case is: I want a column to be nullable in my database but I don't want the field to be required in the input; if the value isn't passed in the input I want to perform some calculation on the server-side.

**Comment by goldcaddy77** [comment]
Did you mean you want it nullable in the GraphQL schema, but required (non-nullable) in the DB, then you'd default if not provided?

**Comment by ikoenigsknecht** [comment]
Correct.  I don't want it to be required that the user include it when creating an object, but required in the database.

**Comment by goldcaddy77** [comment]
Gotcha. I’d actually prefer to use a different API in this case. There are 3 options:

1. Have the options for `nullable` be `true`, `false`, `dbOnly` and `apiOnly`
2. Add `dbOptions` and `apiOption` to the decorator for more granular control
3. Use a separate `CustomField` decorator when you want to go off the beaten path like this

Will think on this, but leaning towards 3. For now you could use a GraphQL default or just leave it non-nullable until it’s supported.

**Comment by goldcaddy77** [comment]
Check out https://github.com/goldcaddy77/warthog/pull/250/files#diff-984f57b34defd9f4be76f9d2e7979a8cR113-R116

```typescript
 @CustomField({
    api: { type: 'json', nullable: true },
    db: { type: 'geometry', spatialFeatureType: 'Point', nullable: false }
  })
  geometryField: object;
```

This would allow you the flexibility in these edge cases without muddying up the API for the common cases.

**Comment by goldcaddy77** [comment]
Published in version 2.0.0-beta.8

**Pull request closed without merging**
